In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [2]:
from sklearn import linear_model
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
Data = load_breast_cancer()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB

In [3]:
lr=linear_model.LogisticRegression()
dt=DecisionTreeClassifier()
bn=BernoulliNB()

In [4]:
df=pd.DataFrame(Data.data, columns=Data.feature_names)
df["target"]=pd.Series(Data.target)

In [5]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [6]:
df2=df.sample(frac=1)

In [7]:
df2.shape

(569, 31)

In [8]:
hold_on_data=df2.iloc[0:285,:]

In [9]:
hold_on_data.shape

(285, 31)

In [10]:
hold_on_data

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
74         12.31         16.52           79.19      470.9          0.09172   
430        14.90         22.53          102.10      685.0          0.09947   
182        15.70         20.31          101.20      766.6          0.09597   
383        12.39         17.48           80.64      462.9          0.10420   
477        13.90         16.62           88.97      599.4          0.06828   
..           ...           ...             ...        ...              ...   
210        20.58         22.14          134.70     1290.0          0.09090   
118        15.78         22.91          105.70      782.6          0.11550   
25         17.14         16.40          116.00      912.7          0.11860   
428        11.13         16.62           70.47      381.1          0.08151   
45         18.65         17.60          123.70     1076.0          0.10990   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
74            0.06829         0.03372              0.02272         0.1720   
430           0.22250         0.27330              0.09711         0.2041   
182           0.08799         0.06593              0.05189         0.1618   
383           0.12970         0.05892              0.02880         0.1779   
477           0.05319         0.02224              0.01339         0.1813   
..                ...             ...                  ...            ...   
210           0.13480         0.16400              0.09561         0.1765   
118           0.17520         0.21330              0.09479         0.2096   
25            0.22760         0.22290              0.14010         0.3040   
428           0.03834         0.01369              0.01370         0.1511   
45            0.16860         0.19740              0.10090         0.1907   

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
74                  0.05914  ...          23.21            89.71       611.1   
430                 0.06898  ...          27.57           125.40       832.7   
182                 0.05549  ...          32.82           129.30      1269.0   
383                 0.06588  ...          23.13            95.23       600.5   
477                 0.05536  ...          21.80           101.20       718.9   
..                      ...  ...            ...              ...         ...   
210                 0.05024  ...          27.84           158.30      1656.0   
118                 0.07331  ...          30.50           130.30      1272.0   
25                  0.07413  ...          21.40           152.40      1461.0   
428                 0.06148  ...          20.29            74.35       421.1   
45                  0.06049  ...          21.32           150.60      1567.0   

     worst smoothness  worst compactness  worst concavity  \
74            0.11760            0.18430           0.1703   
430           0.14190            0.70900           0.9019   
182           0.14140            0.35470           0.2902   
383           0.14270            0.35930           0.3206   
477           0.09384            0.20060           0.1384   
..                ...                ...              ...   
210           0.11780            0.29200           0.3861   
118           0.18550            0.49250           0.7356   
25            0.15450            0.39490           0.3853   
428           0.10300            0.06219           0.0458   
45            0.16790            0.50900           0.7345   

     worst concave points  worst symmetry  worst fractal dimension  target  
74                0.08660          0.2618                  0.07609       1  
430               0.24750          0.2866                  0.11550       0  
182               0.15410          0.3437                  0.08631       0  
383               0.09804          0.2819                  0.11180       1  
477               0.06222          0.2679                  0.076

In [11]:
df1=df2.iloc[286:569,:]

In [12]:
y=df1.iloc[:,-1]

In [13]:
y

54     0
484    1
544    1
258    0
224    1
      ..
342    1
233    0
70     0
532    1
53     0
Name: target, Length: 283, dtype: int64

In [14]:
X=df1.iloc[:,:-1]

In [15]:
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
54         15.10         22.02           97.26      712.8          0.09056   
484        15.73         11.28          102.80      747.2          0.10430   
544        13.87         20.70           89.77      584.8          0.09578   
258        15.66         23.20          110.20      773.5          0.11090   
224        13.27         17.02           84.55      546.4          0.08445   
..           ...           ...             ...        ...              ...   
342        11.06         14.96           71.49      373.9          0.10330   
233        20.51         27.81          134.40     1319.0          0.09159   
70         18.94         21.31          123.60     1130.0          0.09009   
532        13.68         16.33           87.76      575.5          0.09277   
53         18.22         18.70          120.30     1033.0          0.11480   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
54            0.07081         0.05253              0.03334         0.1616   
484           0.12990         0.11910              0.06211         0.1784   
544           0.10180         0.03688              0.02369         0.1620   
258           0.31140         0.31760              0.13770         0.2495   
224           0.04994         0.03554              0.02456         0.1496   
..                ...             ...                  ...            ...   
342           0.09097         0.05397              0.03341         0.1776   
233           0.10740         0.15540              0.08340         0.1448   
70            0.10290         0.10800              0.07951         0.1582   
532           0.07255         0.01752              0.01880         0.1631   
53            0.14850         0.17720              0.10600         0.2092   

     mean fractal dimension  ...  worst radius  worst texture  \
54                  0.05684  ...         18.10          31.69   
484                 0.06259  ...         17.01          14.20   
544                 0.06688  ...         15.05          24.75   
258                 0.08104  ...         19.85          31.64   
224                 0.05674  ...         15.14          23.60   
..                      ...  ...           ...            ...   
342                 0.06907  ...         11.92          19.90   
233                 0.05592  ...         24.47          37.38   
70                  0.05461  ...         24.86          26.58   
532                 0.06155  ...         15.85          20.20   
53                  0.06310  ...         20.60          24.13   

     worst perimeter  worst area  worst smoothness  worst compactness  \
54            117.70      1030.0            0.1389             0.2057   
484           112.50       854.3            0.1541             0.2979   
544            99.17       688.6            0.1264             0.2037   
258           143.70      1226.0            0.1504             0.5172   
224            98.84       708.8            0.1276             0.1311   
..               ...         ...               ...                ...   
342            79.76       440.0            0.1418             0.2210   
233           162.70      1872.0            0.1223             0.2761   
70            165.90      1866.0            0.1193             0.2336   
532           101.60       773.4            0.1264             0.1564   
53            135.10      1321.0            0.1280             0.2297   

     worst concavity  worst concave points  worst symmetry  \
54            0.2712               0.15300          0.2675   
484           0.4004               0.14520          0.2557   
544           0.1377               0.06845          0.2249   
258           0.6181               0.24620          0.3277   
224           0.1786               0.09678          0.2506   
..               ...                   ...             ...   
342           0.2299               0.10750         

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [17]:
X

array([[ 0.44487681,  0.63854787,  0.38244015, ...,  0.71261045,
        -0.33474125, -0.30043469],
       [ 0.64741369, -1.81948701,  0.64174566, ...,  0.58377049,
        -0.54333925, -0.11945089],
       [ 0.04944767,  0.33644303,  0.03186285, ..., -0.68398176,
        -1.08781538,  0.06329574],
       ...,
       [ 1.67938729,  0.47605209,  1.61531148, ...,  1.14042522,
        -0.55394593, -1.05492561],
       [-0.01163488, -0.6637071 , -0.06221731, ..., -0.37691317,
        -0.10316212, -0.35390718],
       [ 1.44791658, -0.12129159,  1.46085152, ...,  0.37399259,
         0.2769105 , -0.23344718]])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [19]:
lr.fit(X_train,y_train)
dt.fit(X_train,y_train)
bn.fit(X_train,y_train)

BernoulliNB()

In [20]:
h_X=hold_on_data.iloc[:,:-1]
h_y=hold_on_data.iloc[:,-1]

In [21]:
h_X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
74         12.31         16.52           79.19      470.9          0.09172   
430        14.90         22.53          102.10      685.0          0.09947   
182        15.70         20.31          101.20      766.6          0.09597   
383        12.39         17.48           80.64      462.9          0.10420   
477        13.90         16.62           88.97      599.4          0.06828   
..           ...           ...             ...        ...              ...   
210        20.58         22.14          134.70     1290.0          0.09090   
118        15.78         22.91          105.70      782.6          0.11550   
25         17.14         16.40          116.00      912.7          0.11860   
428        11.13         16.62           70.47      381.1          0.08151   
45         18.65         17.60          123.70     1076.0          0.10990   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
74            0.06829         0.03372              0.02272         0.1720   
430           0.22250         0.27330              0.09711         0.2041   
182           0.08799         0.06593              0.05189         0.1618   
383           0.12970         0.05892              0.02880         0.1779   
477           0.05319         0.02224              0.01339         0.1813   
..                ...             ...                  ...            ...   
210           0.13480         0.16400              0.09561         0.1765   
118           0.17520         0.21330              0.09479         0.2096   
25            0.22760         0.22290              0.14010         0.3040   
428           0.03834         0.01369              0.01370         0.1511   
45            0.16860         0.19740              0.10090         0.1907   

     mean fractal dimension  ...  worst radius  worst texture  \
74                  0.05914  ...         14.11          23.21   
430                 0.06898  ...         16.35          27.57   
182                 0.05549  ...         20.11          32.82   
383                 0.06588  ...         14.18          23.13   
477                 0.05536  ...         15.14          21.80   
..                      ...  ...           ...            ...   
210                 0.05024  ...         23.24          27.84   
118                 0.07331  ...         20.19          30.50   
25                  0.07413  ...         22.25          21.40   
428                 0.06148  ...         11.68          20.29   
45                  0.06049  ...         22.82          21.32   

     worst perimeter  worst area  worst smoothness  worst compactness  \
74             89.71       611.1           0.11760            0.18430   
430           125.40       832.7           0.14190            0.70900   
182           129.30      1269.0           0.14140            0.35470   
383            95.23       600.5           0.14270            0.35930   
477           101.20       718.9           0.09384            0.20060   
..               ...         ...               ...                ...   
210           158.30      1656.0           0.11780            0.29200   
118           130.30      1272.0           0.18550            0.49250   
25            152.40      1461.0           0.15450            0.39490   
428            74.35       421.1           0.10300            0.06219   
45            150.60      1567.0           0.16790            0.50900   

     worst concavity  worst concave points  worst symmetry  \
74            0.1703               0.08660          0.2618   
430           0.9019               0.24750          0.2866   
182           0.2902               0.15410          0.3437   
383           0.3206               0.09804          0.2819   
477           0.1384               0.06222          0.2679   
..               ...                   ...             ...   
210           0.3861               0.19200         

In [22]:
h_X=sc.fit_transform(h_X)

In [23]:
x1=lr.predict(h_X)
x2=dt.predict(h_X)
x3=bn.predict(h_X)

In [24]:
x1

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [25]:
x2

array([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [26]:
x3

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [27]:
df3=pd.DataFrame(data=[x1,x2,x3])

In [28]:
df4=df3.T

In [29]:
df4

0  1  2
0    1  1  1
1    0  0  0
2    0  0  0
3    1  1  1
4    1  1  1
..  .. .. ..
280  0  0  0
281  0  0  0
282  0  0  0
283  1  1  1
284  0  0  0

[285 rows x 3 columns]

In [30]:
lr2=LogisticRegression()

In [31]:
df4_X=df4.iloc[:,:]
df4_Y=h_y

In [32]:
df4_X

0  1  2
0    1  1  1
1    0  0  0
2    0  0  0
3    1  1  1
4    1  1  1
..  .. .. ..
280  0  0  0
281  0  0  0
282  0  0  0
283  1  1  1
284  0  0  0

[285 rows x 3 columns]

In [33]:
df4_Y

74     1
430    0
182    0
383    1
477    1
      ..
210    0
118    0
25     0
428    1
45     0
Name: target, Length: 285, dtype: int64

In [34]:
lr2.fit(df4_X,df4_Y)

LogisticRegression()

In [35]:
X_test=sc.fit_transform(X_test)

In [36]:
X_test

array([[ 3.11535127,  1.20065282,  3.05235346, ...,  1.50468969,
        -0.66783126, -0.41016569],
       [ 0.71031375,  0.97547227,  0.59991129, ..., -0.25343877,
        -0.05728555, -0.07617704],
       [-0.9818822 , -0.83253077, -1.01196101, ..., -1.31040982,
        -1.17174646, -0.863436  ],
       ...,
       [ 0.26077403,  1.14599735,  0.21940833, ..., -0.74133352,
        -0.78994041, -0.64030913],
       [-0.93371723, -1.27196077, -0.991836  , ..., -1.22342958,
        -0.41845343, -0.43495756],
       [-0.42959054, -0.32095554, -0.44144059, ..., -0.16404241,
         0.09234115, -0.44618407]])

In [37]:
x4=lr.predict(X_test)
x5=dt.predict(X_test)
x6=bn.predict(X_test)

In [38]:
df5=pd.DataFrame(data=[x4,x5,x6])

In [39]:
df6=df5.T

In [40]:
df6

0  1  2
0   0  0  0
1   1  1  1
2   1  1  1
3   1  1  1
4   1  1  1
.. .. .. ..
89  0  0  0
90  1  1  1
91  1  1  1
92  1  1  1
93  1  1  1

[94 rows x 3 columns]

In [41]:
df6_X=df6.iloc[:,:]


In [42]:
final=lr2.predict(df6_X)

In [43]:
from sklearn.metrics import accuracy_score

In [44]:
accuracy_score(y_test, final)


0.9361702127659575

In [45]:
precision = precision_score(y_test, final, average=None)
recall = recall_score(y_test, final, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [0.94444444 0.93103448]
recall: [0.89473684 0.96428571]


In [46]:
from sklearn.ensemble import StackingClassifier

In [47]:
df_X=df.iloc[:,:-1]
df_y=df.iloc[:,-1]

In [48]:
df_X=sc.fit_transform(df_X)

In [49]:
df_X.shape

(569, 30)

In [50]:
df_X_train, df_X_test, df_y_train, df_y_test = train_test_split(df_X, df_y, test_size=0.33)

In [51]:
estimators=[('lr',LogisticRegression()),('dt',DecisionTreeClassifier()),('bn',BernoulliNB())]

In [52]:
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())

In [53]:
clf.fit(df_X_train,df_y_train)

StackingClassifier(estimators=[('lr', LogisticRegression()),
                               ('dt', DecisionTreeClassifier()),
                               ('bn', BernoulliNB())],
                   final_estimator=LogisticRegression())

In [54]:
final1=clf.predict(df_X_test)

In [55]:
accuracy_score(df_y_test, final1)

0.9787234042553191

In [56]:
precision = precision_score(df_y_test, final1, average=None)
recall = recall_score(df_y_test, final1, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1.         0.96581197]
recall: [0.94666667 1.        ]
