In [1]:
import numpy as np
import io
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

In [2]:
from google.colab import files
uploaded = files.upload()
data = pd.read_csv(io.BytesIO(uploaded['BuyComputer.csv']))
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Saving BuyComputer.csv to BuyComputer.csv


Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [3]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

# Declare label as last column in the source file

In [4]:
#Declaring X as all columns excluding last
X = data.iloc[:,:-1].values

#Declare label as last column in the source file
Y = data.iloc[:,-1].values


In [5]:
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [6]:
# Splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =  train_test_split(X,Y ,
                                   random_state=104, 
                                   test_size=0.25, 
                                   shuffle=True)

In [7]:
from os import XATTR_SIZE_MAX
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [8]:
X_train

array([[ 0.39245   ,  0.28266692],
       [-0.25956345, -0.41912681],
       [-1.09786646,  0.48735675],
       [-0.63214256, -1.58878301],
       [-1.09786646, -1.00395491],
       [ 0.11301566,  1.07218485],
       [ 0.85817389,  1.10142626],
       [-1.00472168, -0.33140259],
       [ 0.39245   ,  0.1657013 ],
       [ 0.11301566,  0.10721849],
       [ 0.01987089,  0.04873568],
       [-0.63214256, -1.03319631],
       [ 1.51018735, -1.26712755],
       [-0.07327389,  0.04873568],
       [ 0.85817389,  1.27687469],
       [-1.65673513,  0.37039113],
       [-0.07327389, -0.21443697],
       [-1.37730079, -1.20864474],
       [-0.81843212,  0.39963254],
       [-0.81843212,  0.1657013 ],
       [-0.07327389,  0.31190832],
       [ 0.29930522, -0.18519557],
       [ 0.48559478,  1.24763328],
       [ 1.04446345,  2.09563403],
       [-0.72528734, -1.5303002 ],
       [ 1.78962168, -1.26712755],
       [ 0.39245   ,  1.13066766],
       [ 1.88276646,  2.18335824],
       [ 0.85817389,

In [9]:
X_test

array([[-1.17093376e+00, -1.21972933e+00],
       [-2.00285827e+00, -8.02931412e-01],
       [-9.62952626e-01,  3.87919774e-01],
       [ 8.04886969e-01, -1.33881445e+00],
       [-1.48290545e+00, -1.47963260e-01],
       [ 3.88924711e-01, -5.64761175e-01],
       [-2.70375467e-02,  6.55861291e-01],
       [ 1.11685866e+00,  1.87648376e+00],
       [-1.89886771e+00, -1.33881445e+00],
       [-2.35018676e-01, -9.81559090e-01],
       [ 1.42883035e+00,  2.23373911e+00],
       [ 1.63681148e+00,  2.14442527e+00],
       [-1.48290545e+00, -6.83846293e-01],
       [ 1.11685866e+00,  1.99556887e+00],
       [ 1.22084923e+00, -9.51787810e-01],
       [ 3.88924711e-01,  3.06644180e-02],
       [ 1.80943582e-01,  1.79520816e-01],
       [ 9.08877533e-01, -1.16018677e+00],
       [ 7.00896404e-01, -9.51787810e-01],
       [-5.46990369e-01,  1.37037200e+00],
       [-2.70375467e-02,  2.68834655e-01],
       [ 8.04886969e-01, -1.45789956e+00],
       [-2.35018676e-01,  5.07004892e-01],
       [-8.

In [10]:
#Variabes to calculate sigmoid function
y_pred = []
len_x = len(X_train[0])
w = []
b = 0.2
print(len_x)

2


In [11]:
entries = len(X_train[:,0])


In [12]:
entries

300

In [13]:
for weights in range(len_x):
  w.append(0)

In [14]:
w

[0, 0]

In [15]:
def sigmoid(z):
  return (1/(1+np.exp(-z)))


In [16]:
def predict(inputs):
  z=np.dot(inputs,w)+b
  h=sigmoid(z)
  for i in range((len(h))):
    if(h[i]>=0.5):
      h[i]=1
    else:
      h[i]=0
  return h
  


In [17]:
#y

In [18]:
from scipy.optimize.minpack import shape
def loss_func(y,y1):
  total_loss=np.sum(-y*np.log(y1)-(1-y)*np.log(1-y1))
  m=y.shape[0]
  j=total_loss/m
  return j

In [19]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
  dw.append(0)

In [ ]:
l1=[]
for i in range(3000):
    z = np.dot(X_train, w) + b
    y_pred = sigmoid(z)
    l = loss_func(y_train, y_pred)
    l1.append(l)
    dw = np.dot((y_pred-y_train).T, X_train)/X_train.shape[0]
    db = np.mean(y_pred-y_train)
    w = w - alpha * dw
    b = b - alpha* db
    print("Round:",i,"Weight:",w,"Bias:",b,"loss:",l)

Round: 0 Weight: [0.03011143 0.01578386] Bias: 0.1806832669354189 loss: 0.7268055360482587
Round: 1 Weight: [0.05942141 0.0310715 ] Bias: 0.16184655964417666 loss: 0.7117219622937114
Round: 2 Weight: [0.08795049 0.04587778] Bias: 0.14348103568382808 loss: 0.6974414469909611
Round: 3 Weight: [0.11572014 0.06021809] Bias: 0.12557701558232098 loss: 0.6839223980058162
Round: 4 Weight: [0.14275248 0.07410816] Bias: 0.1081241348135145 loss: 0.6711239863741537
Round: 5 Weight: [0.16907007 0.08756391] Bias: 0.09111148767396685 loss: 0.6590064296551772
Round: 6 Weight: [0.19469571 0.10060127] Bias: 0.0745277607798548 loss: 0.647531218072165
Round: 7 Weight: [0.21965222 0.11323614] Bias: 0.05836135469582014 loss: 0.6366612873692978
Round: 8 Weight: [0.2439623  0.12548419] Bias: 0.042600492898884325 loss: 0.6263611434699795
Round: 9 Weight: [0.26764841 0.13736085] Bias: 0.02723331785340774 loss: 0.6165969446695337
Round: 10 Weight: [0.29073264 0.14888117] Bias: 0.012247974424029778 loss: 0.607336

In [ ]:
X_train


In [ ]:
y_pred=predict(X_test)

In [ ]:
y_pred

In [ ]:
#print actual and predicted values in a table
print("actual Value\tpredicted values")
for i in range(len(y_test)):
    print(y_test[i],"\t\t",int(y_pred[i]))

In [ ]:
x=0
for i in range(len(y_test)):
  if(y_test[i]==y_pred[i]):
    x+=1
print((x/len(y_test))*100)


In [ ]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
from sklearn.metrics import  accuracy_score
#Fit
LR.fit(X_train,y_train)

#predicting the test label with LR. Predict always takes X as input
y_test_pred = LR.predict(X_test)
accuracy = accuracy_score(y_test, y_test_pred)*100
print("Accuracy: ", accuracy,"%")

In [ ]:
precision = precision_score(y_test, y_test_pred, average=None)
recall = recall_score(y_test, y_test_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

In [ ]:
import matplotlib.pyplot as plt
l1=np.array(l1)

In [ ]:
len(l1)

In [ ]:
l1

In [ ]:
x=np.array(range(0,3000))

In [ ]:
x

In [ ]:
plt.plot(x,l1)

In [ ]:
hello1=np.array([[28,76000]])


In [ ]:
hello1=np.array(hello1)

In [ ]:
hello1

In [ ]:
x_ask=sc.fit(hello1)

In [ ]:
x_ask=x_ask.transform(hello1)

In [ ]:
x_ask

In [ ]:
LR.predict(x_ask)